name: Build on Ubuntu

on:
  push:
    branches:
      - master
      - v*

    paths:
      - src/**
      - meson.build

  pull_request:
    paths:
      - src/**
      - meson.build

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install git meson build-essential libluajit-5.1-dev libmysqlclient-dev
          libboost-date-time-dev libboost-iostreams-dev libboost-system-dev libpugixml-dev
          libcrypto++-dev libfmt-dev

      - name: Build with meson
        run: meson setup -D buildtype=release ${{ runner.workspace }}/build && ninja -C ${{ runner.workspace }}/build

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-tfs-amd64-${{ github.sha }}
          path: ${{ runner.workspace }}/build/tfs
